name: Build and deploy master

on:
  push:
    branches:
    - master
    tags:
    - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build NBTEditor
      working-directory: ./plugin
      run: ./compile-nbteditor.sh
    - name: Deploy to Github Package Registry
      working-directory: ./plugin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir -p ~/.m2
        echo "<settings><servers><server><id>github</id><username>x-access-token</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
        ./deploy.sh
